version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Yangon"
    target-branch: "devel"
    labels:
      - "dependencies"
    pull-request-branch-name:
      separator: "-"
